### ISSUE TITLE
建议添加和无尽贪婪mod的联动物品

### ISSUE THREAD

**Issue by xgbbv** [KELETU66666/IchoriumKit#2]
![big_pearl](https://github.com/KELETU66666/IchoriumKit/assets/125100598/0bcc1223-484e-4f2d-a86c-a3c15a6bcf3c)
极元始珍珠

![akashic_record](https://github.com/KELETU66666/IchoriumKit/assets/125100598/9b66f14d-61bb-4e97-a47e-52b240a5ee2a)
阿卡西记录

![36053c0dce2ba8091f90a37a1f134e9a626f5d3ee1be9c25ba2f2523bb145bdc 0](https://github.com/KELETU66666/IchoriumKit/assets/125100598/508d916e-adbe-4993-a3a6-79f0e26c73f0)
水晶镶嵌宇宙中子素法师护手

**Comment by xgbbv** [comment]
水晶镶嵌宇宙中子素法师护手
贴图的来源
来自于神秘杂项学 mod

**Comment by KELETU66666** [comment]
reject
