### ISSUE TITLE
Game crashed after the latest update

### ISSUE THREAD

**Issue by InterPlay02** [KELETU66666/IchoriumKit#4]
Hi there!

My game crashed when initializing.
It was running correctly before. The crash happened after updating the mod for the newest version.

Here is the log file:
https://github.com/InterPlay02/Random-Codes/blob/principal/latest.log

Your mod is awesome, btw!

**Comment by KELETU66666** [comment]
sorry, my bad, i'll fix it now

**Comment by KELETU66666** [comment]
i reupload it, if solved, pls close this issue, thank you :)

**Comment by InterPlay02** [comment]
Now the game is loading correctly.
Thank you for your attention. I'm closing this.
