### ISSUE TITLE
Random crash with Celestial Pearl

### ISSUE THREAD

**Issue by xJon** [KELETU66666/IchoriumKit#5]
Happened when messed with it in creative - https://mclo.gs/nNzczrr

**Comment by KELETU66666** [comment]
let me see...

**Comment by KELETU66666** [comment]
oh, this is caused by placement mirror, i'll fix it soon :)
![image](https://github.com/KELETU66666/IchoriumKit/assets/92129388/5d5f82fa-2ab2-4b12-acbe-1799e99fabd5)

**Comment by KELETU66666** [comment]
finally fixed :)
